server.port=8081

# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/v3/api-docs

# (Redundante pero útil) delimitar por propiedades también
springdoc.packages-to-scan=com.proxyproject.products_service.controllers
springdoc.paths-to-match=/api/products/**

# FakeStore base URL
fakestore.base-url=https://fakestoreapi.com
